version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.14.2-browsers-legacy
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build
          command: yarn build
      - run:
          name: Install examples
          command: (cd example/yarn && yarn) && (cd example/lerna && yarn)
      - run:
          name: Test
          command: yarn test
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
